services:
  dev:
    build:
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    command: /bin/bash -c "/workspace/.devcontainer/scripts/init.sh"
    stdin_open: true
  redis:
    restart: always
    image: redis:latest
  nats:
    restart: always
    image: nats:latest
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
