services:
  dev:
    build:
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    command: /bin/bash -c "/workspace/.devcontainer/scripts/init.sh"
    stdin_open: true
  nats:
    restart: always
    image: nats:latest
  casdoor:
    image: casbin/casdoor:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      # Configure Casdoor to use SQLite3
      RUN_MODE: "dev"
      DRIVER_NAME: "sqlite3"
      DATA_SOURCE_NAME: "/data/casdoor.db"
    volumes:
      - ./casdoor-data:/data
  redis:
    restart: always
    image: redis:latest