services:
  dev:
    build:
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    command: /bin/bash -c "/workspace/.devcontainer/scripts/init.sh"
    stdin_open: true
  redis:
    image: redis:latest
